<?php if ($strdate = $block->getCountdownTime()): ?>
    <div class="cdt-container">
        <div id="countdown">
            <ul>
                <li><span id="days"></span><?php echo __('days')?></li>
                <li><span id="hours"></span><?php echo __('Hours')?></li>
                <li><span id="minutes"></span><?php echo __('Minutes')?></li>
                <li><span id="seconds"></span><?php echo __('Seconds')?></li>
            </ul>
        </div>
    </div>

    <script>
    var kstDateString = "<?php echo $strdate?>"; // KST
    var kstDate = new Date(kstDateString);
    var offset = kstDate.getTimezoneOffset();
    var targetDate = new Date(kstDate.getTime() - (offset * 60 * 1000)); // Local Date

    function formatTime(unit) { return unit.toString().padStart(2, '0'); }
    
    (function () {
        const second = 1000, minute = second * 60, hour = minute * 60, day = hour * 24;
        const countDown = targetDate.getTime(),
            x = setInterval(function() {    

                const now = new Date().getTime(), distance = countDown - now;

                document.getElementById("days").innerText = Math.floor(distance / (day)),
                document.getElementById("hours").innerText = Math.floor((distance % (day)) / (hour)),
                document.getElementById("minutes").innerText = Math.floor((distance % (hour)) / (minute)),
                document.getElementById("seconds").innerText = Math.floor((distance % (minute)) / second);

                //do something later when date is reached
                if (distance < 0) {
                    document.getElementById("countdown").style.display = "none";
                    clearInterval(x);
                }
                //seconds
            }, 0)
    }());
    </script>
<?php endif; ?>

