<?php if ($strdate = $block->getCountdownTime()): ?>
    <div class="cdt-container">
        <div id="countdown">
            <ul>
                <li><span id="days"></span><?php echo __('days')?></li>
                <li><span id="hours"></span><?php echo __('Hours')?></li>
                <li><span id="minutes"></span><?php echo __('Minutes')?></li>
                <li><span id="seconds"></span><?php echo __('Seconds')?></li>
            </ul>
        </div>
    </div>

    <script>
    var datestring = "<?php echo $strdate?>";
    var target_date = new Date(datestring);
    target_date = new Date(target_date + ' UTC+09:00');

    function formatTime(unit) { return unit.toString().padStart(2, '0'); }
    
    (function () {
        const second = 1000, minute = second * 60, hour = minute * 60, day = hour * 24;

        //I'm adding this section so I don't have to keep updating this pen every year :-)
        //remove this if you don't need it
        let today = new Date(),
            dd = String(today.getDate()).padStart(2, "0"),
            mm = String(today.getMonth() + 1).padStart(2, "0"),
            yyyy = today.getFullYear(),
            nextYear = yyyy + 1,
            dayMonth = "09/30/",
            birthday = dayMonth + yyyy;
        
        today = mm + "/" + dd + "/" + yyyy;
        if (today > birthday) {
            birthday = dayMonth + nextYear;
        }
        //end
        
        const countDown = target_date.getTime(),
            x = setInterval(function() {    

                const now = new Date().getTime(), distance = countDown - now;

                document.getElementById("days").innerText = Math.floor(distance / (day)),
                document.getElementById("hours").innerText = Math.floor((distance % (day)) / (hour)),
                document.getElementById("minutes").innerText = Math.floor((distance % (hour)) / (minute)),
                document.getElementById("seconds").innerText = Math.floor((distance % (minute)) / second);

                //do something later when date is reached
                if (distance < 0) {
                    document.getElementById("countdown").style.display = "none";
                    clearInterval(x);
                }
                //seconds
            }, 0)
    }());
    </script>
<?php endif; ?>

